Finished Seat Issue
saishravanm/Ad-Mission pull request #24
Opened 2024-03-29 20:53 UTC by Jpkidd02

2024-03-29 21:41 UTC, saishravanm approved these changes

2024-03-29 22:15 UTC, raj-thapa approved these changes, later dismissed

2024-04-01 21:16 UTC, raj-thapa requested changes

2024-04-01 21:16 UTC, raj-thapa commented on frontend/ad-mission/src/App.vue
No end for script tag.

2024-04-01 21:16 UTC, raj-thapa commented on backend/Routes/routes.js
For the seats, please make seatroutes.js and add all your functions there.

2024-04-14 17:46 UTC, merged